#* ************************************************************************** *#
#*                                                                            *#
#*                                                        :::      ::::::::   *#
#*   Makefile                                           :+:      :+:    :+:   *#
#*                                                    +:+ +:+         +:+     *#
#*   By: cbaillat <cbaillat@student.42.fr>          +#+  +:+       +#+        *#
#*                                                +#+#+#+#+#+   +#+           *#
#*   Created: 2017/11/13 18:12:06 by cbaillat          #+#    #+#             *#
#*   Updated: 2017/11/14 18:28:12 by cbaillat         ###   ########.fr       *#
#*                                                                            *#
#* ************************************************************************** *#

NAME = libft.a

CC = gcc
FLAGS = -Wall -Werror -Wextra -O3

SOURCEDIR = ./
HEADERDIR = ./
BUILDDIR = build
SOURCES =	$(SOURCEDIR)/ft_memset.c \
			$(SOURCEDIR)/ft_bzero.c \
			$(SOURCEDIR)/ft_memcpy.c \
			$(SOURCEDIR)/ft_memccpy.c \
			$(SOURCEDIR)/ft_memmove.c \
			$(SOURCEDIR)/ft_memchr.c \
			$(SOURCEDIR)/ft_memcmp.c \
			$(SOURCEDIR)/ft_strlen.c \
			$(SOURCEDIR)/ft_strdup.c \
			$(SOURCEDIR)/ft_strcpy.c \
			$(SOURCEDIR)/ft_strncpy.c \
			$(SOURCEDIR)/ft_strcat.c \
			$(SOURCEDIR)/ft_strncat.c \
			$(SOURCEDIR)/ft_strlcat.c \
			$(SOURCEDIR)/ft_strchr.c \
			$(SOURCEDIR)/ft_strrchr.c \
			$(SOURCEDIR)/ft_strstr.c \
			$(SOURCEDIR)/ft_strnstr.c \
			$(SOURCEDIR)/ft_strcmp.c \
			$(SOURCEDIR)/ft_strncmp.c \
			$(SOURCEDIR)/ft_atoi.c \
			$(SOURCEDIR)/ft_isalpha.c \
			$(SOURCEDIR)/ft_isdigit.c \
			$(SOURCEDIR)/ft_isalnum.c \
			$(SOURCEDIR)/ft_isascii.c \
			$(SOURCEDIR)/ft_isprint.c \
			$(SOURCEDIR)/ft_toupper.c \
			$(SOURCEDIR)/ft_tolower.c \
			$(SOURCEDIR)/ft_memalloc.c \
			$(SOURCEDIR)/ft_memdel.c \
			$(SOURCEDIR)/ft_strnew.c \
			$(SOURCEDIR)/ft_strdel.c \
			$(SOURCEDIR)/ft_strclr.c \
			$(SOURCEDIR)/ft_striter.c \
			$(SOURCEDIR)/ft_striteri.c \
			$(SOURCEDIR)/ft_strmap.c \
			$(SOURCEDIR)/ft_strmapi.c \
			$(SOURCEDIR)/ft_strequ.c \
			$(SOURCEDIR)/ft_strnequ.c \
			$(SOURCEDIR)/ft_strsub.c \
			$(SOURCEDIR)/ft_strjoin.c \
			$(SOURCEDIR)/ft_strtrim.c \
			$(SOURCEDIR)/ft_strsplit.c \
			$(SOURCEDIR)/ft_itoa.c \
			$(SOURCEDIR)/ft_putchar.c \
			$(SOURCEDIR)/ft_putstr.c \
			$(SOURCEDIR)/ft_putendl.c \
			$(SOURCEDIR)/ft_putnbr.c \
			$(SOURCEDIR)/ft_putchar_fd.c \
			$(SOURCEDIR)/ft_putstr_fd.c \
			$(SOURCEDIR)/ft_putendl_fd.c \
			$(SOURCEDIR)/ft_putnbr_fd.c \

OBJECTS = $(patsubst $(SOURCEDIR)/%.c, $(BUILDDIR)/%.o, $(SOURCES))

.PHONY: all setup clean fclean re

all: setup $(NAME)

$(NAME): $(OBJECTS)
	@echo "[Linking] "$(NAME)
	ar rsc $(NAME) $(OBJECTS)

$(BUILDDIR)/%.o: $(SOURCEDIR)/%.c
	@echo "[Compiling] "$@
	$(CC) $(FLAGS) -I $(HEADERDIR) -c $< -o $@

setup:
	@mkdir -p $(BUILDDIR)

clean:
	@echo "[Cleaning objects]"
	/bin/rm -f $(OBJECTS)

fclean: clean
	@echo "[Cleaning binary]"
	/bin/rm -f $(NAME)
	@echo "[Clean!]"

re: fclean all
